version: '3.1'

services:
  app:
    build: ./
    ports:
      - 3000:3000
    networks:
      - local
    depends_on:
      - mysql_db
    restart: always
    volumes:
      - ./:/app
  mysql_db:
    container_name: mysql_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - local
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: app_db

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    networks:
      - local
    ports:
      - 8080:8080

networks:
  local: