version: 2.1

orbs:
  node: circleci/node@4.7
  terraform: circleci/terraform@3.0.0

jobs:  
  install-and-build:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - run:
          command: yarn
          name: Install dependencies
      - run:
          command: yarn build
          name: Build distributable
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  deploy-prod:
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          command: ls -a
      - run:
          command: >-
            sh ./infrastructure/scripts/configure-tfvars.sh
          name: Configure .tfvars file
      - run:
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
          name: Create .terraformrc file locally
      - terraform/init:
          path: ./infrastructure
      - terraform/validate:
          path: ./infrastructure
      - terraform/fmt:
          path: ./infrastructure
      - terraform/plan:
          path: ./infrastructure
      - terraform/apply:
          path: ./infrastructure

workflows:
  version: 2
  deploy:
    jobs:
      - install-and-build
      - deploy-prod:
          requires:
            - install-and-build
          filters:
            branches:
              only:
                - master
