version: 2.1

orbs:
  node: circleci/node@4.7
  terraform: circleci/terraform@3.0.0

jobs:
  deploy-prod:
    environment:
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
      AWS_DEFAULT_REGION: ''

    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: ./infrastructure
      - terraform/validate:
          path: ./infrastructure
      - terraform/fmt:
          path: ./infrastructure
      - terraform/plan:
          path: ./infrastructure
      - terraform/apply:
          path: ./infrastructure

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-prod:
        filters:
          branches:
            only:
              - master
